# Generated by Django 4.0.2 on 2023-01-24 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lan',
        ),
        migrations.AddField(
            model_name='product',
            name='lan',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_lan', to='store.language'),
            preserve_default=False,
        ),
    ]
